### ISSUE TITLE
Simple email sharing

### ISSUE THREAD

**Issue by Slipkipu** [koddr/goodshare.js#18]
Hi,

goodshare.js is great, however, I miss the simple email share button, there is one for Russia, but not the general email share button. 

Is it possible to add it ? 

Thanks in advance,

**Comment by enjoyiacm** [comment]
We have open code — you may do anything you want, including email share button!

**Comment by Slipkipu** [comment]
Thanks for a quick reply.
Yes I understood that we could change the code, but I 'm not a good coder, that's why I was asking :/

**Comment by Slipkipu** [comment]
Thanks for a quick reply.

After searching , I find how to generate sharing by email link.
However, I have a small question, when I click on the email share button, I have a pop-up that opens, then the mailbox to send my email, is there not a solution to prevent the first pop-up opens ? 
Here is my code:
`/*
			 *  Share link > email
			 */
			em: function(_options) {
				var options = $.extend({
					body:    location.href,
					subject:  document.title,
				}, _options);
				return 'mailto:?'
					+ 'subject='      + encodeURIComponent(options.title)
					+ '&body='        + encodeURIComponent(options.url);
			},`
Thank you in advance.

**Comment by eliot-akira** [comment]
Here is the line that is creating the popup (currently line 46):

https://github.com/koddr/goodshare.js/blob/06ec3e6556ff86cbd29a4c0e664e71d8aa632b24/goodshare.js#L46

To prevent the popup from your email share button, you can change this:

```js
if (self.popup(link = self[options.type](options)) !== null) return false;
```

..to..

```js
var link = self[options.type](options);
if (options.type === 'em') {
  window.location.href = link;
  return false;
} else if (self.popup(link) !== null) return false;
```

**Comment by koddr** [comment]
Since `4.0.0` we don't support jQuery version. If you want to add something amazing to `goodshare.js` – write pull-request, using new dir structure and ES6.
