### ISSUE TITLE
Вопрос по fb и ok

### ISSUE THREAD

**Issue by rosivanov** [koddr/goodshare.js#30]
При шаринге fb и ok, в url попапа не передаются data-text и data-image.
Речь об этом участке http://joxi.ru/krD7od1IEM0qQA
Вопрос поддерживают ли fb и ok передачу описания, и картики в url попапа? Например для vk в url передаются все data- параметры.

**Comment by koddr** [comment]
То, что вы хотите узнать – относится к jQuery версии плагина, который более не поддерживается.
