### ISSUE TITLE
Двузначный код

### ISSUE THREAD

**Issue by ebilyy** [koddr/goodshare.js#31]
В атрибутах data-type и data-counter нужно указывать двузначный код из таблицы «Список поддерживаемых социальных сетей и микроблогов».
При использовании двузначного кода эта либа не работает. Работает только при использовании  data-type="facebook" ...

**Comment by koddr** [comment]
Да, многое поменялось со времён использования, в качестве плагина jQuery. Теперь нужно указывать не `data-type`, а `data-social` с полным наименованием соц. сети.
