### ISSUE TITLE
Клик по элементам, которые добавились после загрузки страницы

### ISSUE THREAD

**Issue by taraskhvyl** [koddr/goodshare.js#32]
Если, к примеру, я вставляю элементы для шаринга скриптом, то клик по ним не дает никакого действия. То есть event работает только для элементов, которые уже были на странице

**Comment by koddr** [comment]
Можете написать обертку над goodshare.js, которая будет обновлять основной скрипт. С удовольствием примим в качестве pull-request.

**Comment by taraskhvyl** [comment]
С es6 не особо близок, поэтому переписал ваш старый скрипт под себя. Можем вести параллельно версии)

**Comment by Shmasya** [comment]
Старый был намного минималистичней и удобней.
