### ISSUE TITLE
VK счетчик

### ISSUE THREAD

**Issue by sergey-sedoy** [koddr/goodshare.js#34]
Неверно работает счетчик ВК. Пример ответа API: VK.Share.count(1, 95); Вы берете первое значение, а нужно второе. Так же было бы неплохо суммировать показатели http и https.

**Comment by sergey-sedoy** [comment]
Так же проблема присутствует с ОК. Аналогично: ODKL.updateCount('1','0'); нужно брать второе значение.

**Comment by sergey-sedoy** [comment]
Весь JS крашится на Android, WP и ТВ.

**Comment by koddr** [comment]
Можете прислать PR с исправлениями?

По Андроид и прочим: как воспроизвести «крушение» скрипта? Больше конкретики, ибо при наших тестах всё работает, как задумано.
