### ISSUE TITLE
counter for custom url 

### ISSUE THREAD

**Issue by skvarovski** [koddr/goodshare.js#36]
Здравствуйте, 
а можно без пересборки задавать url, например через data-url для подсчета лайков? и почему-то не работает VK когда вписываешь url внутри js файла (с фейсбуком все нормально)

в моей задаче интересно было бы использовать ваше решение но со страницей, где например голосовалка в виде лайков поэтому чей заданый url победит тот и выиграет.

**Comment by koddr** [comment]
Приветствую!

Можно конкретнее про нерабочий VK? Как мне воспроизвести этот баг, чтобы протестировать?

Для вашей задачи не обойтись без дописывания кода внутри обработчика по клику. Поэтому делать пересборку, всё же, придётся.

**Comment by skvarovski** [comment]
Спасибо за ответ!
В моем случае был редактирован код goodshare.js - закоментирован и переназначен url внутри функции vkontakte на 1831 строке, посл этого был запуск index.html (c вызовом goodshare.js) так вот он не работал ни в каком случае.... возвращается всегда 1 , но в случае подмены url в facebook() на 472 строке все определяется нормально.
