### ISSUE TITLE
Доработки скрипта.

### ISSUE THREAD

**Issue by Arkadiy-Sedelnikov** [koddr/goodshare.js#37]
Здравствуйте. Я для своих нужд доработал ваш скрипт. Сделал возможность использования нескольких блоков шары с различными урл на одной странице, получение информации об урл, заголовке, описании, изображении для шары из data-аттрибутов ссылки. Хотелось бы видеть это у вас. Могу поделать пулл-реквесты, если это нужно. Измененный файл прилагаю.
[goodshare.js.zip](https://github.com/koddr/goodshare.js/files/884394/goodshare.js.zip)

**Comment by LITVIN0V** [comment]
Здравствуйте. 
Использовал Ваш доработанный скрипт. Работает, но у меня почему-то не считает количество кликов по кнопке.
В оригинальном скрипте считал. Это мой косяк при установке или нужно еще чего-то поправить?

**Comment by Arkadiy-Sedelnikov** [comment]
http://poligon3.argens.ru/content посмотрите здесь. Возможно еще нужно изменить разметку.

**Comment by koddr** [comment]
@Arkadiy-Sedelnikov доброго времени года! Да, сделайте пулл-реквест, рассмотрим и примем.

**Comment by Arkadiy-Sedelnikov** [comment]
Есть разобранные скрипты в папках dist и src и собранный скрипт. В какие файлы вносить изменения?

**Comment by koddr** [comment]
В dev ветку, чтобы потом скомпилировать мы смогли на своей стороне.

**Comment by Arkadiy-Sedelnikov** [comment]
Перед внесением изменений собрал скрипт из сорцев, получилась вот такая ошибка http://joxi.ru/J2b6kDeIXBBE62 Когда удалил модуль буффера ошибка пропала, но счетчики не заработали. Делал командами npm install и npm run dev.

**Comment by Arkadiy-Sedelnikov** [comment]
Запустил бабел, файл .babelrc игнорируется гит и не передается, в package.json для бабела нет настроек, добавил, запустил, получил рабочий скрипт.
