### ISSUE TITLE
Object doesn't support this property or method "from"

### ISSUE THREAD

**Issue by andrey-hohlov** [koddr/goodshare.js#39]
Hi!

Got an error in IE11 and IE10:

```
Object doesn't support this property or method "from"
```

**Comment by koddr** [comment]
Hello. Can you share your OS version and console error screenshot?

**Comment by andrey-hohlov** [comment]
@koddr 
Windows 10 + IE11: http://joxi.ru/MAjpYB8f488xpm
Windows 7 + IE10: http://joxi.ru/eAODpWgux77kWr

In app.js: `@import goodshare.js`; (build with webpack)

Same error if include goodshare.min.js in html file
```
<script src="goodshare.min.js">
```

**Comment by koddr** [comment]
@andrey-hohlov what's your Webpack version and packing configuration?

**Comment by andrey-hohlov** [comment]
@koddr 

It does not matter because same error I have without webpack.
Look at minimal example: 

Just this html: 
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <script src="goodshare.min.js"></script>
</body>
</html>
```
And `goodshare.min.js` downloaded from link in readme.

Does goodshare support IE10 and IE11 or not?

If not, I will include polyfill in my app.js. But in this case you need write about it in readme.

**Comment by koddr** [comment]
@andrey-hohlov 

Oh, thx for reason. Yes, goodshare.js 4.x rewrited with ECMAScript 6 and do not support IE11- (check supported table: https://kangax.github.io/compat-table/es6/#ie11). But old version (before 4.x) worked fine on IE7+ ('cause included jQuery depences).
