### ISSUE TITLE
Обработка события получения всех счетчиков.

### ISSUE THREAD

**Issue by Voral** [koddr/goodshare.js#42]
Нет ли возможности (или в планах) добавить возможность привязать свою функцию на событие поучение всех ответов? (Или просто при получении отдельного ответа с признаком соцсети)?

**Comment by koddr** [comment]
В планах много чего есть, только времени это реализовывать — в данный момент нет совершенно. Кстати, ищу со-мейнтейнера на этот репозиторий. Если есть желание, то милости прошу.
