### ISSUE TITLE
Change default text source

### ISSUE THREAD

**Issue by aliajoudanian** [koddr/goodshare.js#44]
Hi,
Goodshare uses description meta tag's content as a text for share. I couldn't find any way to change it. I don't want to use my description to share in twitter.
Is there any way to change text source?

**Comment by koddr** [comment]
This on TODO list. The plan is: add ```data-*``` attr for title, description and image. If you may help — welcome 👍

**Comment by marcelogarbin** [comment]
> This on TODO list. The plan is: add `data-*` attr for title, description and image. If you may help — welcome 👍

Hello, I started using this package today, I found it interesting and very fast. But I would like to know if this question of data customization is working.

Does it work on localhost or only online?

**Comment by koddr** [comment]
@marcelogarbin Hi! Thx.

You may serve downloaded repository by simple Python 3 CLI snippet:

```console
# for macOS/Linux and, maybe, on Windows WSL:

$ git clone https://github.com/koddr/goodshare.js.git
$ cd goodshare.js
$ python3 -m http.server 8080 --bind 127.0.0.1 --directory ./
```

And now, go to browser to see `goodshare.js` example page:

```console
http://127.0.0.1:8080/example
```
