### ISSUE TITLE
Snapchat: The Snapchat is not working through the social share 

### ISSUE THREAD

**Issue by aminul-xs** [koddr/goodshare.js#444]
**Description:** All the social share items need to be checked. I have checked around 7 items. Among them, Snapchat and flicker are not working.  

https://d.pr/i/mE2rBd/2tOFoq1e6U

**Comment by ahmedrezik2002** [comment]
![image](https://user-images.githubusercontent.com/121868662/210355027-aec3b828-8a0b-4ac6-be30-63aeb0714e91.png)
