### ISSUE TITLE
Google Plus doesn't work

### ISSUE THREAD

**Issue by TiagoDeSousa** [koddr/goodshare.js#46]
Google Plus with counter doesn't work. It doesn't show counter number and gplus pop-up shows the following error message: 
"That link isn't valid. Check it and try again."

**Comment by andidrea** [comment]
I'm not sure about your pop-up problem but the counter is related to the Yahoo query:

/**/goodshare_02760609047923396({"query":{"count":"0","created":"2017-06-16T12:09:45Z","lang":"en-US","meta":{"message":"html table is no longer supported. See https://policies.yahoo.com/us/en/yahoo/terms/product-atos/yql/index.htm for YQL Terms of Use"}},"results":[]});

**Comment by TiagoDeSousa** [comment]
Sorry but I really don't understand your reply. All I know is that Google Plus share button with counter doesn't work for me. It also doesn't work on the demo as well.
Thanks.

**Comment by andidrea** [comment]
The counter does a request to a Yahoo API to get the Google+ counter. This request gives the above error message. So the counter for Google+ doesn't work with the current version of goodshare.

The reason for your pop-up error "That link isn't valid. Check it and try again." might be different.

**Comment by TiagoDeSousa** [comment]
Thanks for the explanation. So can it be fixed then?

**Comment by taraskhvyl** [comment]
@TiagoDeSousa  @andidrea 
hi. to remove error before author update plugin u can replace part of code for google plus counter with it:
`if (count_elements.length > 0) {
      window[callback] = (counter) => {
        [...count_elements].forEach((item) => {
          if(counter.results[0]) {
                item.innerHTML = ((counter.results[0]).match(/javascript">window.__SSR = \{c: (\d+).0/) !== null)
                    ? (counter.results[0]).match(/javascript">window.__SSR = \{c: (\d+).0/)[1] / 1
                    : 0;
            } else {
                item.innerHTML = 0;
            }
        });
        script.parentNode.removeChild(script);
      };
      script.src = count_url;
      document.body.appendChild(script);
    }`

after it compile

**Comment by koddr** [comment]
Fix this at f632e7fc04d7c6cd21f8cbce1fca5fea673cdabc
