### ISSUE TITLE
Facebook doesn't work

### ISSUE THREAD

**Issue by TiagoDeSousa** [koddr/goodshare.js#47]
Facebook with counter doesn't work. It shows counter number 0 however you can't share anything and get this error message:
"Sorry, this feature isn't available right now: An error occurred while processing this request. Please try again later."

**Comment by koddr** [comment]
Error message looks like Facebook API was changes, but I don't found in docs another way to add this feature.. If you know, please send me link or pull request with this changes.

**Comment by dmitrylebedev** [comment]
@koddr, @TiagoDeSousa, I've just updated facebook share url, and it's work

```js
export let facebook_share = new Facebook(
  'https://www.facebook.com/dialog/feed?app_id=145634995501895&display=popup&caption=An%20example%20caption&link=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fdialogs%2F&redirect_uri=https://developers.facebook.com/tools/explorer', // URL
).shareWindow();
```

see please: https://stackoverflow.com/questions/20956229/has-facebook-sharer-php-changed-to-no-longer-accept-detailed-parameters
