### ISSUE TITLE
Array.from() ошибка в ie

### ISSUE THREAD

**Issue by rosivanov** [koddr/goodshare.js#49]
Здравствуйте! Обнаружилась ошибка в ie11, связана с отсутствием поддержки метода Array.from()
версия "goodshare.js": "^4.0.6"
http://joxi.ru/krD7od1IEWjMBA
http://joxi.ru/52aJDoNu4Bz9PA

Могли бы вы добавить полифилл для метода? Вот рабочий полифилл https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from?v=control#Polyfill
Заранее спасибо!

**Comment by koddr** [comment]
Добрый день. Пришлите, пожалуйста, пулл-реквест с этими изменениями, рассмотрю и добавлю.
