### ISSUE TITLE
List of attributes

### ISSUE THREAD

**Issue by rosivanov** [koddr/goodshare.js#50]
Здравствуйте! В версии 3 были доступны настройки через data атрибуты https://github.com/koddr/goodshare.js/tree/3.2.9#list-of-attributes
Есть ли способ такой настройки в v4?

**Comment by koddr** [comment]
Добрый день. Пока что такую возможность не рассматриваю, ввиду нехватки времени на развитие проекта. Если есть желание, то присылайте пулл-реквест с данным функционалом. Рассмотрю и добавлю в основную ветку.

**Comment by rosivanov** [comment]
@koddr Добрый день, такой вариант добавления data- подойдет? https://github.com/rosivanov/goodshare.js/commit/7e2671d20b9043dd3ab0289822fac57081b41b5e
