### ISSUE TITLE
Перенос всех поставленных лайков со старых кнопок на goodshare

### ISSUE THREAD

**Issue by DmitryMugik** [koddr/goodshare.js#52]
А можно перенести все поставленные лайки со старых (официальных) кнопок на Ваши.

**Comment by koddr** [comment]
Официальные, так же как и goodshare.js, кнопки работают по принципу реального нахождения лайков в системе. В свою очередь, goodshare.js берёт эти данные из API социальной сети, а не сохраняет их где-то у себя в БД. Поэтому, переносить ничего не нужно.

**Comment by DmitryMugik** [comment]
У меня есть соц. кнопки офф. например Вконтакте с apiId: 3597674 как мне перенести на goodshare.js

**Comment by DmitryMugik** [comment]
Вернее не перенести, а чтоб считывало с определенного id

**Comment by DmitryMugik** [comment]
Все понял, объяснения не требуется! Спасибо за Вашу работу!
