### ISSUE TITLE
Refreshing when new links added to page dynamically

### ISSUE THREAD

**Issue by garethsprice** [koddr/goodshare.js#54]
How would I go about refreshing Goodshare to re-scan the page for social links?

Use case is when new articles are loaded into the page via AJAX. Currently as the links are injected into the page after Goodshare is included, the links have correct data-social attributes but do not have Goodshare events attached.

**Comment by Wayfindertm** [comment]
Include goodshare script after share buttons, or in the end of container which you are load via ajax

**Comment by devxom** [comment]
@Wayfindertm This will not solve the problem of updating the data when you need to dynamically update this for sharing. For example, when dynamically on the front-end or the back-end you generate a collage for the items selected for the sharing.

**Comment by Wayfindertm** [comment]
Тут вопрос был касательно аякс контента, вложение скрипта внутрь аякс контента заставит повесить обработчики после добавления на страницу. В одном из проектов так и пришлось делать.

**Comment by devxom** [comment]
@Wayfindertm in a situation where on the page has a lot of blocks added dynamically. Provided that they contain share logic. When you add a script tag with a reference to the library in each of the blocks. 
We will create additional requests to the server even if further serviceworker or cache. Extra DOM elements will be created. Also, we lose the ability to flexibly update the data on the fly. Also, we can't put the library in our gang with this approach.

**Comment by Wayfindertm** [comment]
А нельзя изначально вешать обработчик не на элемент а на документ с селектором по дата атрибутам, а счетчики обновлять только у вновь созданных?

**Comment by devxom** [comment]
@Wayfindertm 
- Initially, according to the author's logic, handlers are hung only on target elements without using event delegation.
- When using event delegation, we increase the load on the user's browser a bit more.
- When you use delegation, you increase the requirement for the environment in which you add the library. 
- For such logic, we will have to store a little more data in memory. Which will allow operating events and handlers?
- For the correct implementation of such logic will have to complicate the logic of the library. As a consequence and increase weight.
- Implementation in PR updates not only counters but also re-reads data for sharing.

The implementation of you're suggesting is not wrong, but I think it's a little bit specific. Interesting what think author.

**Comment by Wayfindertm** [comment]
@devxom Спасибо за столь развернутый ответ, честно говоря я особо не задумывался на сколько это отразится на потреблении памяти и размере библиотеки.
