### ISSUE TITLE
Callback for success share

### ISSUE THREAD

**Issue by taraskhvyl** [koddr/goodshare.js#57]
Hi.

How can I get callback after success share?

Thank you.

**Comment by devxom** [comment]
I began to work on the task

**Comment by devxom** [comment]
After a cursory examination of the issue, I see two solutions. Each of which is not absolutely stable.

**Option 1:**

* When creating a window with a ball, get a "link to the window object."
* Iteratively check that the window still exists.
* In a situation where the window has already closed, assume that the user has share link.
* Calling the logic handler for share

**Option 2:**

* When creating a window with a ball, get a "link to the window object."
* Iteratively check that the window still exists.
* In a situation where the window has already closed, assume that the user has share link.
* when the window is closed, we run the verification logic that the link was really shared.
* Calling the logic handler for share

There will be a problem with the logic of verification, it will greatly increase the size of the library, and will not be stable in view of the majority of social networks.

It seems to be sufficient to implement 1 option to cover most needs.
