### ISSUE TITLE
Don`t wokr data parametrs

### ISSUE THREAD

**Issue by gaz12** [koddr/goodshare.js#58]
Hi.
For the share link I want to put a picture and a title. Here is my link: `<a href="#" data-title="test title" data-social="facebook" data-image="/telecom/img/share3.png"> <i class = "fa fa-facebook" > </ i> </a>`
As a result I have this https://snag.gy/u0Ni34.jpg
Where was I wrong?

**Comment by koddr** [comment]
Hi. Try to clear Facebook sharer cache here: https://developers.facebook.com/tools/debug/sharing/

**Comment by gaz12** [comment]
Thank you!
