### ISSUE TITLE
Facebook sharing doesn't seem to work

### ISSUE THREAD

**Issue by jannhama** [koddr/goodshare.js#63]
I tried Facebook, Twitter and LinkedIn sharing and while Twitter and LinkedIn seem to work, Facebook gives an error in the sharing dialog. Error says something like: "This functionality is not available now. Error while processing the request. Try again later."

**Comment by koddr** [comment]
@jannhama Hello!

Can you share screenshot of this error from Google Chrome console (or else)? And please send me part of your code, who created share buttons.

Thanks.

**Comment by jannhama** [comment]
Here is my code and screencapture:
`<a href="#" data-social="facebook"><div class="social-icon-box"><i class="fa fa-facebook" aria-hidden="true"></i></div></a>`
![image](https://user-images.githubusercontent.com/958523/35390308-9be4d51c-01e3-11e8-84cb-269cb0c8c0f3.png)

**Comment by koddr** [comment]
What's link do you share?

**Comment by jannhama** [comment]
The page where I'm currently in my browser

**Comment by koddr** [comment]
@jannhama if this link is something like `localhost` or `127.0.0.1`, some social networks **doesn't work** correctly. And I still do not understand your environment and what code do you use for make social sharing. Maybe errors something into your other code, who knows?

**Comment by jannhama** [comment]
Yeah, I'm running dev server (Hugo) on my local machine. This is the only code I use: `<a href="#" data-social="facebook"><div class="social-icon-box"><i class="fa fa-facebook" aria-hidden="true"></i></div></a>`

**Comment by koddr** [comment]
> Yeah, I'm running dev server (Hugo) on my local machine.

That's answer. Script working correctly only on production server.
