### ISSUE TITLE
Add chinese social media

### ISSUE THREAD

**Issue by mohamine18** [koddr/goodshare.js#64]
## Overview of the problem
Wechat, Sino Weibo, QQ are missing from the social media list

**Comment by koddr** [comment]
@mohamine18 can you please send me links for APIs of this social media?

If they have methods for share links to it — I will add it to `goodshare.js`.

**Comment by mohamine18** [comment]
Unfortunately, they have only Chinese documentation, I will try with my team to contribute :)

**Comment by koddr** [comment]
Added: WeChat, Weibo, RenRen.
