### ISSUE TITLE
Facebook, Googleplus and Stumbleupon Cannot Share The Correct Data

### ISSUE THREAD

**Issue by Oxibug** [koddr/goodshare.js#68]
## Overview of the problem
Hi Guys,

1. It seems like the facebook and googleplus cannot get the correct URL or anything else, The old version can get the image and the post title and description but now it can get the main URL only like [https://domain.com]

2. Stumbleupon convert into mix.com and it no longer available so the share URLs generates 

```
<a class="goodshare" href="#" 
data-social="facebook" 
data-url="https://oxibug.com/example/2018/08/07/cannot-use-facebook-and-googleplus-share/" 
data-title="Cannot use Facebook and Googleplus Share Buttons" 
data-description="It seems like theres a problem" 
data-image="https://oxibug.com/example/wp-content/uploads/2018/07/35.jpg">

    <i class="socicon socicon-facebook"></i>

</a>

<a class="goodshare" href="#" 
data-social="googleplus" 
data-url="https://oxibug.com/example/2018/08/07/cannot-use-facebook-and-googleplus-share/" 
data-title="Cannot use Facebook and Googleplus Share Buttons" 
data-description="It seems like theres a problem" 
data-image="https://oxibug.com/example/wp-content/uploads/2018/07/35.jpg">

    <i class="socicon socicon-googleplus"></i>

</a>

```

### Screenshots
1. [Facebook Issue](https://awscdn.oxibug.com/cdn/wp-content/uploads/2018/08/goodshare-js-fb-gp-issue-08-18.png)

2. [Stumbleupon Issue](https://awscdn.oxibug.com/cdn/wp-content/uploads/2018/08/goodshare-js-stumbleupon-issue.png)

## Steps to Reproduce

1.
2.
3.

## Configuration

- Browser: Chrome 68
- OS/Device: Windows 8.1
- goodshare.js: 5.1.1

**Comment by Oxibug** [comment]
Hi @koddr .. Do you need more info from me??

**Comment by Oxibug** [comment]
Hi @koddr .. If the fixes will take a lot of time just notify me to use the old version until you release the new one.

Thanks pal

**Comment by koddr** [comment]
Fix StumbleUpon share counter by switching to [Mix](https://mix.com).
Facebook share counter works fine.
