### ISSUE TITLE
Does not work sharing in Odnoklassniki

### ISSUE THREAD

**Issue by enemy-senator92** [koddr/goodshare.js#69]
## Overview of the problem

Hello, does not work sharing in Odnoklassniki

### Screenshots

https://i.imgur.com/TMgrE8u.png

## Steps to Reproduce

1. Install plugin
2. Set classname elements
3. Click to elements
4. An error window opens

## Configuration

- Browser: all
- OS/Device: all
- goodshare.js: v5.1.1

**Comment by zverush** [comment]
Link need to change on
https://connect.ok.ru/offer?url=URL_TO_SHARE&title=TITLE

**Comment by koddr** [comment]
Fixed, `5.1.2`
