### ISSUE TITLE
Popup centering logic doesn't work correctly on multiple monitors

### ISSUE THREAD

**Issue by philwolstenholme** [koddr/goodshare.js#74]
## Overview of the problem

Hi, thanks for your work!

It looks like the popup centering logic isn't quite right for multiple monitor setups (see screenshots below)

It looks like you could fix this by copying this example: https://github.com/BrandwatchLtd/twitter-intents/blob/master/twitter-intents.js#L30 

The example above works perfectly for me on my three monitor setup :)

### Screenshots

**Primary desktop monitor, works great:**

![primary-desk-monitor](https://user-images.githubusercontent.com/6339853/54839947-cccf9280-4cc3-11e9-86aa-198322921652.png)

**Secondary desktop monitor, vertically centered but not horizontally:**

![secondary-desk-monitor](https://user-images.githubusercontent.com/6339853/54839980-dd800880-4cc3-11e9-969f-b8057175475b.png)
 
**Laptop screen, appears in top right hand corner**

<img width="1435" alt="third-laptop-screen" src="https://user-images.githubusercontent.com/6339853/54840015-ecff5180-4cc3-11e9-9c3f-d4d15262bccf.png">

## Steps to Reproduce

1. Open `/goodshare/goodshare.js/example/index.html` and click on a provider link in a multiple monitor setup

## Configuration

- Browser: Chrome, latest
- OS/Device: Mac OS
- goodshare.js: 6.0.4

**Comment by koddr** [comment]
@philwolstenholme yes, yes.. I know this trouble, I have 2 screens too :D 

Promise, I fix it as soon as possible. Thanks 👍

**Comment by koddr** [comment]
@philwolstenholme I try to use Twitter code sample, but it does not work.

I research this thing, but if you have more samples|examples — would be great to share them to me :)
