### ISSUE TITLE
Facebook messenger support, in your roadmap ?

### ISSUE THREAD

**Issue by laurent-d** [koddr/goodshare.js#76]
Hi,

Thanks for your rocking lib !!!
Do you have plan to add facebook messenger on Goodshare ?
It will be great :D 

Have a good day !!

**Comment by koddr** [comment]
Hello, @laurent-d 

Sharing to Facebook already added to goodshare.js lib.

If you mean [this](https://developers.facebook.com/docs/sharing/messenger/web/) thing, it works only at mobile devices. Second thing is Messenger app be installed otherwise link will be broken.

**Comment by laurent-d** [comment]
Hi @koddr,
Thanks a lot for the support and the quick reply !
I didn't know sorry
