### ISSUE TITLE
Having error with whatsapp

### ISSUE THREAD

**Issue by dgillier** [koddr/goodshare.js#79]
Hello,

I'm trying to use goodshare.js with whatsapp.

I'm using :
<button type="button" data-social="whatsapp" data-title="{{$course->title}}" data-description="{{$course->description}}" data-image="{{ URL::asset('img/brand/bms-favicon.png') }}" class="btn btn-slack btn-icon-label">
    <span class="btn-inner--icon"><i class="fab fa-whatsapp"></i></span>
    <span class="btn-inner--text">WhatsApp</span>
</button>

And I'm getting an error on whatsapp 
(url : https://api.whatsapp.com/resolve?deeplink=/%3Ftext%3Dhttps%253A%252F%252Fxxxxxxx.ngrok.io%252Fcourses%252Fclass-cyrill-11-06-2020)

<img width="1150" alt="Screenshot 2020-06-11 at 14 35 58" src="https://user-images.githubusercontent.com/37960204/84386024-e4f53f80-abf0-11ea-9252-b32d6c32fa4b.png">

Any idea what I'm doing wrong ?
Thanks, Denis

**Comment by koddr** [comment]
@dgillier Hi!

Can you please share your code example?

**Comment by dgillier** [comment]
oh sorry...
Here it is:

                         <button type="button" data-social="whatsapp" data-title="{{$course->title}}" data-description="Test" data-image="{{ URL::asset('img/brand/bms-favicon.png') }}" class="mt-2 btn btn-slack btn-icon-label" style="min-width:12rem;">
                                            <span class="btn-inner--icon"><i class="fab fa-whatsapp"></i></span>
                                            <span class="btn-inner--text">WhatsApp</span>
                                        </button>

**Comment by koddr** [comment]
Thx!

I see, you missed `data-url`. Try to add this attribute.

**Comment by dgillier** [comment]
Thanks, I was lazy (though if no data-url, plugin will get document url ;)
 Unfortunetly got the same error  with:

<button type="button" data-social="whatsapp" data-title="Test" data-url="https://xxxxxx.ngrok.io/courses/test-01-06-2020" data-description="test" data-image="https://xxxxxx.ngrok.io/img/brand/bms-favicon.png" class="mt-2 btn btn-slack btn-icon-label" style="min-width:12rem;">
             <span class="btn-inner--icon"><i class="fab fa-whatsapp"></i></span>
             <span class="btn-inner--text">WhatsApp</span>
 </button>

**Comment by koddr** [comment]
>  Unfortunetly got the same error  with: [...]

Hmm... 🤔  Can you please share screenshot with errors in your browser's console?

**Comment by dgillier** [comment]
looked at your code :


  getPreparedData(item) {
    const url = item.dataset.url
      ? encodeURIComponent(item.dataset.url)
      : this.url;
    const share_url = `https://wa.me/?text=${url}`;

    return {
      callback: this.callback,
      share_url: share_url,
      windowTitle: "Share this",
      windowWidth: 640,
      windowHeight: 480
    };
  }

Looks like anything send to https://wa.me/ is returning the same error, so maybe they change API ?

**Comment by koddr** [comment]
Yep, API was changed.

I fix it today.

**Comment by dgillier** [comment]
Thanks !

**Comment by koddr** [comment]
Fix at `v6.1.5`

Thanks for reply! 👍
